/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_really_quit_dialog (void);
GtkWidget* create_add_module_dialog (void);
GtkWidget* create_about_dialog (void);
GtkWidget* create_machine_popup (void);
GtkWidget* create_machine_popup_1 (void);
GtkWidget* create_rename_dlg (void);
GtkWidget* create_about_module_dialog (void);
GtkWidget* create_create_pattern_dialog (void);
GtkWidget* create_machine_popup_2 (void);
